### PR TITLE
[WIP] import from nmp

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/162#issuecomment-145181526

**Comment by rom1504** [comment]
https://circleci.com/gh/rom1504/Protocols/2

**Comment by rom1504** [comment]
Might want to import from master:
* cstring
* range

**Comment by rom1504** [comment]
used in https://github.com/PrismarineJS/node-minecraft-protocol/pull/274

**Comment by roblabla** [comment]
There are other small details in ProtoDef I'd like to keep : 
- Using createType : https://github.com/roblabla/Protocols/pull/8/files#diff-90dd315c6ff1f1a362e4f42eed5ac7a8L5.
- Some tests that haven't been ported yet

**Comment by rom1504** [comment]
Ah yeah indeed https://github.com/roblabla/Protocols/blob/master/test/datatypes/structures.js need to be ported.

**Comment by rom1504** [comment]
I think structures.js test never worked (it uses undefined variable like offset) and the way we handle arrays (count) changed a lot so there is little point trying to port it, I think it should just be rewritten.

**Comment by rom1504** [comment]
https://github.com/roblabla/ProtoDef/blob/599f8e8229312bf6ae0e0ae5ebc6e08c8ae847b7/lib/utils.js#L42

I really can't see the benefit of createType: it just returns an array of 3 functions like we have currently, and during usage all it does it making use repeat read/write/sizeOf 2 times (see https://github.com/roblabla/ProtoDef/blob/599f8e8229312bf6ae0e0ae5ebc6e08c8ae847b7/lib/datatypes/conditional.js#L5 )

**Comment by rom1504** [comment]
https://github.com/roblabla/ProtoDef/blob/599f8e8229312bf6ae0e0ae5ebc6e08c8ae847b7/lib/stream.js : there's not much to port there, I think we should go the other way round, take nmp stream and change stuff from it.

**Pull request merged**
